@api_server=http://47.111.144.204/api

###
//로그인
POST {{api_server}}/login 
content-type: application/json

{
    "nick": "admin",
    "password": "admin",
    "hospital_id": 1
}
###
//
GET {{api_server}}/control/range?token=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC80Ny4xMTEuMTQ0LjIwNFwvYXBpXC9sb2dpbiIsImlhdCI6MTU3MDc4NDkxMCwiZXhwIjoxNTc0Mzg0OTEwLCJuYmYiOjE1NzA3ODQ5MTAsImp0aSI6ImpVWXQ3eU9wVUgxUXhmUU4iLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.YTO1hUcmi6zGKUEH9WSR3IltmbOIrqxIRfu5_BG0JTs

 HTTP/1.1
content-type: application/json; charset=utf-8
Accept-Charset: utf-8

###
//添加新记录
//department_id, user_id, advice_number, all_number, paper_number, liquid_number, liquid_type, min, max, time, value, result_type, use_number
POST {{api_server}}/control 
content-type: application/json


{
"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC80Ny4xMTEuMTQ0LjIwNFwvYXBpXC9sb2dpbiIsImlhdCI6MTU2ODYwOTM2OCwiZXhwIjoxNTY4NjEyOTY4LCJuYmYiOjE1Njg2MDkzNjgsImp0aSI6IjRsMHdubnl3eUc3czFNVE4iLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.GSGKTmrEZmVMpOLE71GSWO1aJrzgoBbw5fu8fngYRDA",
"department_id":1,
"user_id": 1,
"paper_number": "10:10",
"liquid_number": "2019-09-15",
"liquid_type": 0,
"value": 200,
"result_type": 1,
"use_number": 1,
"time": "2019-09-09"
}

###
//UPDATE
POST {{api_server}}/control/update 
content-type: application/json

{
"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC80Ny4xMTEuMTQ0LjIwNFwvYXBpXC9sb2dpbiIsImlhdCI6MTU2ODUyMTQ2MiwiZXhwIjoxNTY4NTI1MDYyLCJuYmYiOjE1Njg1MjE0NjIsImp0aSI6IkExcTBxNW5vSldQSHphWGciLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.3YW0pynEioJUk-fSdlln8EIvjcIPtS8j7jFqQEpjavM",
"id": 0,
}

###
//DELETE
POST {{api_server}}/control/delete
content-type: application/json

{
"token":"eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJodHRwOlwvXC80Ny4xMTEuMTQ0LjIwNFwvYXBpXC9sb2dpbiIsImlhdCI6MTU2ODU1NDM2MCwiZXhwIjoxNTY4NTU3OTYwLCJuYmYiOjE1Njg1NTQzNjAsImp0aSI6ImpWek1TV3FjSkNPTW5uUWMiLCJzdWIiOjEsInBydiI6Ijg3ZTBhZjFlZjlmZDE1ODEyZmRlYzk3MTUzYTE0ZTBiMDQ3NTQ2YWEifQ.PQyo6eA-dirqn0Oi5sqnt5mIRUBItnskf5HFB1CY55o",
"id": 13,
}



