export { PatientsScreen } from './main/patients.screen';
export { PatientsSatisticScreen } from './statistic/patients.statistic.screen';
export { PatientMainInfoContainer } from './detail/patientInfo/patientMainInfo.screen';
export { GlucoseLogAContainer } from './detail/glucoseLogA/glucoseLogA.screen';
export { GlucoseLogBContainer } from './detail/glucoseLogB/glucoseLogB.screen';
export { ConsultLogContainer } from './detail/consult/consultLog.screen';
export { DoctorsOrderLogContainer } from './detail/doctorsOrder/doctorsOrderLog.screen';
export { InhospitalLogContainer } from './detail/inHospital/inhospitalLog.screen';
export { InsulinOrderContainer } from './detail/insulinOrder/insulinOrder.screen';
export { VisitLogContainer } from './detail/visit/visitLog.screen';
export { ChangeDepartLogScreen } from "./detail/changeDepart/changeDepartLog.screen";
export { GlucoseChartContainer } from './detail/glucoseChart/glucoseChart.screen';
export { GlucoseDayChartContainer } from './detail/glucoseDayChart/glucoseDayChart.screen';
export { TodayTaskContainer } from "./detail/todayTask/todayTask.screen"
export { DetailMainScreen } from "./detail/detailMain.screen";
